version: '3.7'

services:
  relay-controller:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:80
      - 9000:22
    mem_limit: 4G
    cap_add:
      - NET_ADMIN
      - NET_RAW