version: '3.7'

services:
  relay-controller:
    build: .
    volumes:
      - .:/usr/src/app
      - /dev/gpiomem:/dev/gpiomem
      - /dev/mem:/dev/mem
    ports:
      - 8080:80
    mem_limit: 4G
    cap_add:
      - NET_ADMIN
      - NET_RAW